image: python:3.8.10
test:
    stage: test
    before_script:
        - pip install -r requirements.txt
    script:
        - python manage.py migrate
        - python manage.py collectstatic --no-input
        - python manage.py test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

cypress-e2e:
    stage: test
    image: moneymeets/cypress-python
    before_script:
        - pip3 install -r requirements.txt
        - npm install
    script:
        - python3 manage.py migrate
        - python3 manage.py collectstatic --no-input
        # - python3 manage.py runserver & (sleep 5 && npx cypress run)

staging:
    stage: deploy
    image: ruby:latest
    before_script:
        - gem install dpl
        - gem install faraday -v 1.8.0
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY --run='python manage.py migrate && python manage.py loaddata testdb.json'
