image: python:3.8.10
test:
    stage: test
    before_script:
        - pip install -r requirements.txt
    script:
        - python manage.py migrate
        - export DEBUG=True
        - python manage.py collectstatic
        - python manage.py test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

cypress-e2e:
    stage: test
    image: moneymeets/cypress-python
    before_script:
        - pip3 install -r requirements.txt
        - npm install
    script:
        - python3 manage.py migrate
        - export DEBUG=True
        - python3 manage.py collectstatic
        - python3 manage.py runserver & (sleep 2 && npx cypress run)
    artifacts:
        expire_in: 1 week
        when: always
        paths:
            - cypress/screenshots
            - cypress/videos
        reports:
            junit:
                - results/TEST-*.xml


development:
    stage: deploy
    before_script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_DEVELOPMENT --api-key=$HEROKU_API_KEY --run='python manage.py migrate && python manage.py loaddata testdb.json'

staging:
    stage: deploy
    before_script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - gem install faraday -v 1.8.0
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY --run='python manage.py migrate && python manage.py loaddata testdb.json'
    only:
    - master
