databases:
    - name: mysite
      databaseName: mysite
      user: mysite

services:
    - type: web
      name: polls-app
      env: python
      buildCommand: './build.sh'
      startCommand: 'gunicorn django_project.wsgi:application'
      autoDeploy: true
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: mysite
                property: connectionString
          - key: SECRET_KEY
            generateValue: true
