# Generated by Django 4.2.6 on 2023-10-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="name",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="age",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.IntegerField(
                choices=[(1, "Female"), (2, "Male"), (3, "Other")], default=1
            ),
        ),
    ]
