# Generated by Django 4.2.6 on 2023-11-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0002_remove_userprofile_name_alter_userprofile_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_student",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_teacher",
            field=models.BooleanField(default=False),
        ),
    ]
