# Generated by Django 4.2.6 on 2023-11-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0003_userprofile_is_student_userprofile_is_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
    ]
